### ISSUE TITLE
Variables don't use proper standard

### ISSUE THREAD

**Issue by DocCodes** [jchouse/csscomb-atom#39]
## Correct Syntax (CSSComb Complains)
```css
:root {
   --doc-main-bg: #003366;  /* Complaint Here */
}
body {
   background-color: var(doc-main-bg);
}
```

## Years-Old Syntax (CSSComb Approves, but doesn't work anymore)
```css
:root {
   var-doc-main-bg: #003366;  /* All Good (Not Really) */
}
body {
   background-color: var(doc-main-bg);
}
```
